# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker


trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '2304366a-a596-4b67-9a99-4e1ff6b22c82'
  imageRepository: 'dockerdevops'
  containerRegistry: 'deployairflowcicd.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'
stages:
- stage: BuildAndPush
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DockerCompose@0
      inputs:
        azureSubscription: 'Development Subscription (d8501f72-cc6e-4c07-9f8c-b8523c3b63ec)'
        azureContainerRegistry: '{"loginServer":"deployairflowcicd.azurecr.io", "id" : "/subscriptions/d8501f72-cc6e-4c07-9f8c-b8523c3b63ec/resourceGroups/deployairflowcicd/providers/Microsoft.ContainerRegistry/registries/deployairflowcicd"}'
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Build services'
    - task: DockerCompose@0
      inputs:
        azureSubscription: 'Development Subscription (d8501f72-cc6e-4c07-9f8c-b8523c3b63ec)'
        azureContainerRegistry: '{"loginServer":"deployairflowcicd.azurecr.io", "id" : "/subscriptions/d8501f72-cc6e-4c07-9f8c-b8523c3b63ec/resourceGroups/deployairflowcicd/providers/Microsoft.ContainerRegistry/registries/deployairflowcicd"}'
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Push services'
        
